version: "3.3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: upload_laravel
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - upload_laravel

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        container_name: upload_laravel_ngix
        ports: 
            - "8989:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - upload_laravel

    mysql:
        image: mysql:8.0
        restart: unless-stopped
        container_name: upload_laravel_mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - upload_laravel

    redis:
        image: redis:latest
        networks:
            - upload_laravel

networks:
    upload_laravel:
        driver: bridge
